/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import EDD.Cola;
import EDD.Lista;
import EDD.Nodo;
import EDD.PCB;
import EDD.Proceso;
import EDD.Scheduler;

/**
 *
 * @author miche_ysmoa6e
 */
public class Interface extends javax.swing.JFrame {

    private Lista processList = new Lista();
    private Scheduler scheduler;
    private int memorySpace = 4000;
    private Cola readyQueue = new Cola();
    private Cola blockedQueue = new Cola();
    private Cola suspendedQueue = new Cola();
    
    public Cola fillReadyQueue(){
        //Cola readyQueue = new Cola();
        for (int i = 0; i < processList.count(); i++){
            PCB auxProcessPCB = ((Nodo) processList.get(i)).getInfoProceso().getPcb();
            if (auxProcessPCB.getStatus() == "ready"){
                readyQueue.enqueue(processList.get(i));
            } else{
                i++;
            }
        }
        return readyQueue;
    }
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selection = new javax.swing.JTabbedPane();
        sim_panel = new java.awt.Panel();
        panel1 = new java.awt.Panel();
        round_robin_button = new javax.swing.JButton();
        generate_process = new javax.swing.JButton();
        config_panel = new java.awt.Panel();
        label1 = new java.awt.Label();
        statistics_panel = new java.awt.Panel();
        label3 = new java.awt.Label();
        graphics_panel = new java.awt.Panel();
        label4 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulación de planificación - Luis Asenjo, Michelle García");

        selection.setBackground(new java.awt.Color(70, 202, 161));
        selection.setForeground(new java.awt.Color(255, 255, 255));
        selection.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selection.setFocusable(false);

        panel1.setBackground(new java.awt.Color(201, 255, 238));

        round_robin_button.setText("Round robin");
        round_robin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                round_robin_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(round_robin_button)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(round_robin_button)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        generate_process.setText("generar procesos");
        generate_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_processActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sim_panelLayout = new javax.swing.GroupLayout(sim_panel);
        sim_panel.setLayout(sim_panelLayout);
        sim_panelLayout.setHorizontalGroup(
            sim_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sim_panelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(generate_process)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        sim_panelLayout.setVerticalGroup(
            sim_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sim_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(sim_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generate_process)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(338, Short.MAX_VALUE))
        );

        selection.addTab("Simulación", sim_panel);

        label1.setText("aaaaaaaaaaaaa");

        javax.swing.GroupLayout config_panelLayout = new javax.swing.GroupLayout(config_panel);
        config_panel.setLayout(config_panelLayout);
        config_panelLayout.setHorizontalGroup(
            config_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(config_panelLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
        );
        config_panelLayout.setVerticalGroup(
            config_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(config_panelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        selection.addTab("Configuración", config_panel);

        label3.setText("label3");

        javax.swing.GroupLayout statistics_panelLayout = new javax.swing.GroupLayout(statistics_panel);
        statistics_panel.setLayout(statistics_panelLayout);
        statistics_panelLayout.setHorizontalGroup(
            statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
            .addGroup(statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(statistics_panelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        statistics_panelLayout.setVerticalGroup(
            statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(statistics_panelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        selection.addTab("Estadística", statistics_panel);

        label4.setText("label4");

        javax.swing.GroupLayout graphics_panelLayout = new javax.swing.GroupLayout(graphics_panel);
        graphics_panel.setLayout(graphics_panelLayout);
        graphics_panelLayout.setHorizontalGroup(
            graphics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
            .addGroup(graphics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(graphics_panelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        graphics_panelLayout.setVerticalGroup(
            graphics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(graphics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(graphics_panelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        selection.addTab("Gráficos", graphics_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selection)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selection)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void round_robin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_round_robin_buttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_round_robin_buttonActionPerformed

    private void generate_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_processActionPerformed
        
         // 1) Proceso CPU-bound corto (ejemplo: 100 instrucciones)
        Proceso p1 = new Proceso(1, "P1_init", "CPU", 100);
        p1.getPcb().setStatus("ready"); // marcar como listo para ejecución

        // 2) Proceso I/O-bound (con ciclos de I/O)
        Proceso p2 = new Proceso(2, "P2_io", "IO", 200, 5, 2); // ioCicles=5, satisfyCicles=2
        p2.getPcb().setStatus("blocked"); // simula que está esperando I/O

        // 3) Proceso corto/rápido
        Proceso p3 = new Proceso(3, "P3_short", "CPU", 20);
        p3.getPcb().setStatus("ready");

        // Encapsular cada Proceso en un Nodo (constructores definidos en Nodo)
        Nodo n1 = new Nodo(p1);
        Nodo n2 = new Nodo(p2);
        Nodo n3 = new Nodo(p3);
        
        processList.add(n1);
        processList.add(n2);
        processList.add(n3);
        
        this.scheduler = new Scheduler(processList, memorySpace);
        
        /*
        System.out.println("Procesos creados: " + processList.count());
        for (int i = 0; i < processList.count(); i++) {
            Nodo node = (Nodo) processList.get(i);
            Proceso proc = node.getInfoProceso();
            PCB pcb = proc.getPcb();

            int pid = pcb.getId();
            String status = pcb.getStatus();
            String bound = proc.getBound();
            int instr = proc.getInstructions();
            double processingTimeMs = instr * 0.005; // cálculo local (5 ms por instrucción = 0.005 ms por instrucción)
            int memoryKb = instr * 4; // cálculo local (4 KB por instrucción, si esa es la convención)
            boolean needsIo = proc.getIoCicles() > 0;

            System.out.printf("PID=%d | bound=%s | status=%s | instr=%d | procTime=%.3f ms | mem=%d KB | io=%b%n",
                    pid, bound, status, instr, processingTimeMs, memoryKb, needsIo);
        }
        */
    }//GEN-LAST:event_generate_processActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel config_panel;
    private javax.swing.JButton generate_process;
    private java.awt.Panel graphics_panel;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Panel panel1;
    private javax.swing.JButton round_robin_button;
    private javax.swing.JTabbedPane selection;
    private java.awt.Panel sim_panel;
    private java.awt.Panel statistics_panel;
    // End of variables declaration//GEN-END:variables
}
